name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        VERSIONS:
          - WP_VERSION=latest
          - WP_VERSION=5.3 WC_VERSION=4.0.1
          - WP_VERSION=4.9 WC_VERSION=3.5.7
          - WP_VERSION=4.7 WC_VERSION=3.1.2
    steps:
      - uses: actions/checkout@v1
      - uses: php-actions/composer@v1
      - run: cp -v Dockerfile-php7.1 Dockerfile # use old php version
        if: contains(matrix.VERSIONS, 'WP_VERSION=4')
      - run: composer run lint
      - run: ${{ matrix.VERSIONS }} composer run dev
      - run: composer run test
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Test Output
          path: tests/_output
